teams:
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation

repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
